# Project Information
site_name: Knowledge Base
site_description: 'TechTaco Knowledge Base'
site_author: 'Steven Bambling'
site_url: 'http://kb.techtaco.org'
nav:
  - Home: index.md
  - Apple:
      - Administrative: apple/administrative/nav.md
  - Linux:
      - Administrative: linux/administrative/nav.md
      - Apache: linux/apache/nav.md
      - Clustering: linux/clustering/nav.md
      - Puppet: linux/puppet/nav.md
      - GIT: linux/git/nav.md
      - Monitoring: linux/monitoring/nav.md
      - PKI Certificates: linux/pki_certificates/nav.md
      - PostgreSQL: linux/postgresql/nav.md
  - Networking:
      - Cisco: networking/cisco/nav.md
  - 'Tips & Tricks': tips_and_tricks/nav.md
  - Windows:
      - Administrative: windows/administrative/nav.md
      - Outlook: windows/outlook/nav.md

  - Disclaimer: disclaimer.md

# Repository
repo_name: 'techtaco-kb'
repo_url: 'https://github.com/smbambling/techtaco-kb'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Steven Bambling'

# Configuration
theme:
  name: 'material'
  language: 'en'
  logo: 'images/techtaco.png'
  favicon: 'assets/images/favicon.ico'
  palette:
    primary: 'blue'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  feature:
    tabs: false

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/smbambling'
  # disqus: 'techtacoorg'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
